server:
  port: '8082'
  error:
    include-message: always

spring:
  profiles:
    active: dev
---

spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/dcbapp
    password: Qwerty123!@#
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'

welcome:
  message: Hello World!!
management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"

---

spring:
  profiles: qa
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/dcbapp-qa
    password: Qwerty123!@#
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'

welcome:
  message: Hello World!!
